services:
  postgres:
    image: postgres
    container_name: todo-app
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_123
    ports:
      - "5332:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
